  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx2.conf

    depends_on:
      - api1
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"