  ${SERVICE_NAME}:
    image: fastapi/pn_app
    ${BUILD_COMMAND}
    container_name: "${SERVICE_NAME}"
    volumes:
      - ./data:/data
  
    depends_on:
      fastapi_mysql:
        condition: service_healthy       
    ports:
      - ${PORT}:${PORT}
    entrypoint:
      - fastapi
      - run
      - main.py
      - --port 
      - "$PORT"
    