services:
  api1:
    build: .
    container_name: "api1"
    volumes:
      - ./app:/app
    ports:
      - 8001:8001
    entrypoint:
      - fastapi
      - run
      - main.py
      - --port 
      - "8001"
    
  api2:
    build: .
    container_name: "api2"
    volumes:
      - ./app:/app
    ports:
      - 8002:8002
    entrypoint:
      - fastapi
      - run
      - main.py
      - --port 
      - "8002"
    
