services:
  api1:
    build: .
    container_name: "api1"
    volumes:
      - ./app:/app
    ports:
      - 8001:8001
    entrypoint:
      - fastapi
      - run
      - main.py
      - --port 
      - "8001"
    
  api2:
    build: .
    container_name: "api2"
    volumes:
      - ./app:/app
    ports:
      - 8002:8002
    entrypoint:
      - fastapi
      - run
      - main.py
      - --port 
      - "8002"
    
  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
    depends_on:
      - api1
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"