services:
  sqlite:
    image: nouchka/sqlite3:latest
    container_name: sqlite_container
    volumes:
      - ../../container_data/sqlite:/var/lib/sqlite
    stdin_open: true
    tty: true
    command: /var/lib/sqlite/my_new_database.db
