services:
  duns_connect:
    build: .
    image: duns_connect
    container_name: duns_connect_test
    volumes:
      - .:/app
    environment:
      - DUNS_CLIENT_ID=${DUNS_CLIENT_ID}
      - DUNS_CLIENT_SECRET=${DUNS_CLIENT_SECRET}
    stdin_open: true
    tty: true
