services:
 db:
   image: mysql:latest
   container_name: mysql_container
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=pn_user
     - MYSQL_PASSWORD=pn_password
     - MYSQL_DATABASE=pn_crypto_key_store
   volumes:
     - ../../container_data/mysql/pn_crypto_key_store_db:/var/lib/mysql 
     - ./start_up:/docker-entrypoint-initdb.d 

