services:
  company_id_container:
    build: .
    image: comp_mysql
    container_name: company_id_container
    volumes:
      - .:/app
    environment:
      - MYSQL_USER=${PN_MYSQL_USER}
      - MYSQL_PASSWORD=${PN_MYSQL_PASSWORD}
    stdin_open: true
    tty: true
