# use official mysql as base
FROM mysql:latest
RUN mkdir -p /app
WORKDIR /app
# create the directory where host directories will be mounted
RUN mkdir -p /host
RUN mkdir -p /host/mysql
RUN mkdir -p /host/var
